# Generated by Django 2.2.13 on 2020-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.SmallIntegerField(default=0, max_length=2),
        ),
    ]
